version: '3'
services:
  web:
    image: justicedong/jitsi-web:0.0.3
    env_file: .env.web
    volumes:
      - ./jitsi-config/web:/config:Z
    ports:
      - 80:80
      - 443:443
    networks:
      meet.jitsi:
  prosody:
    image: jitsi/prosody:stable-5870
    env_file: .env.prosody
    volumes:
      - ./jitsi-config/prosody/config:/config:Z
    networks:
      meet.jitsi:
  jicofo:
    image: jitsi/jicofo:stable-5870
    env_file: .env.jicofo
    volumes:
      - ./jitsi-config/jicofo:/config:Z
    depends_on:
      - prosody
    networks:
      meet.jitsi:
  jvb:
    image: justicedong/jvb:0.0.2
    env_file: .env.jvb
    volumes:
      - ./jitsi-config/jvb:/config:Z
    ports:
      - "4443:4443"
      - "10000:10000/udp"
    depends_on:
      - prosody
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    networks:
      meet.jitsi:
networks:
  meet.jitsi: