apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: jicofo
  name: jicofo
spec:
  selector:
    matchLabels:
      app: jicofo
  template:
    metadata:
      labels:
        app: jicofo
    spec:
      # avoid that pods of different shards share zone
      nodeSelector:
        topology.kubernetes.io/zone: asia-northeast3-a
      containers:
        - name: jicofo
          env:
            - name: XMPP_SERVER
              value: shard-0-prosody
