apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: jitsi
  name: jvb-hpa
spec:
  minReplicas: 2
  maxReplicas: 2
  scaleTargetRef:
    kind: StatefulSet
    name: shard-0-jvb # needs to be manually set

