apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: jitsi
  name: jvb-hpa
spec:
  maxReplicas: 1
  scaleTargetRef:
    name: jvb-hpa
    apiVersion: apps/v1
    kind: StatefulSet
