apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  retention: 2d
  resources:
    requests:
      memory: 1000Mi
      cpu: 100m
    limits:
      memory: 1000Mi
      cpu: 100m
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: ionos-enterprise-hdd
        resources:
          requests:
            storage: 10Gi
