apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# base project
- https://github.com/coreos/kube-prometheus?ref=release-0.9
# grafana
- grafana-dashboard-configmap.yaml
- grafana-ingress.yaml
- grafana-pvc.yaml
# prometheus
- prometheus-roleBinding.yaml
- prometheus-role.yaml
- prometheus-serviceaccount.yaml
# service monitor
- service-monitor/

patchesStrategicMerge:
  - grafana-deployment-patch.yaml
  - prometheusAdapter-configMap-patch.yaml