apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: jitsi
  name: jvb
spec:
  serviceName: "jvb"
  selector:
    matchLabels:
      app: jvb
  template:
    metadata:
      labels:
        app: jvb
    spec:
      containers:
        - name: prometheus-exporter
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
        - name: jvb
          resources:
            requests:
              cpu: "800m"
              memory: "1000Mi"
            limits:
              cpu: "800m"
              memory: "1000Mi"
