apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: jitsi
spec:
  tls:
  - hosts:
    # fill in host here
    - peopleundercloud.com
    secretName: jitsi-peopleundercloud-tls
